EMS/EMS/urls.py
from django.contrib import admin
from django.urls import path,include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('manage/', include('manage.urls')),
    path('user/', include('user.urls')),
]

EMS/manage/urls.py
from django.urls import path

from manage.views import main, add_employee, confirm_add, delete,update,confirm_update

app_name = 'manage'

urlpatterns = [
    path('main/', main, name='main'),
    path('add/', add_employee, name='add'),
    path('confirm_add/', confirm_add, name='confirm_add'),
    path('delete/', delete, name='delete'),
    path('update/', update, name='update'),
    path('confirm_update/', confirm_update, name='confrim_update')
]

EMS/user/urls.py
from django.urls import path

from user import views

app_name = 'user'

urlpatterns = [
    path('login/', views.login, name='login'),
    path('login_logic/', views.login_logic, name='login_logic'),
    path('register/', views.register, name='register'),
    path('register_logic/', views.register_logic, name='register_logic'),
    path('get_captcha/', views.get_captcha, name='get_captcha'),
    path('log_out/', views.log_out, name='log_out'),
    path('get_username/', views.get_username, name='get_username'),
    path('get_code', views.get_code, name='get_code'),
]

EMS/user/models.py
from django.db import models

# Create your models here.


class User(models.Model):
    username = models.CharField(max_length=20)
    realname = models.CharField(max_length=20)
    password = models.CharField(max_length=20)
    gender = models.CharField(max_length=5)

    class Meta:
        db_table = 'ems_user'

EMS/user/views.py
import random
import string
import time

from django.http import JsonResponse
from django.shortcuts import render, HttpResponse, redirect

from user.captcha.image import ImageCaptcha
from user.models import User


# Create your views here.


def login(request):
    username = request.COOKIES.get('name')
    if username:
        username = username.encode('latin-1').decode('utf-8')
    pwd = request.COOKIES.get('password')
    user = User.objects.filter(username=username, password=pwd)
    if user:
        request.session['flag'] = 1
        return redirect('manage:main')
    return render(request, 'login.html')


def login_logic(request):
    try:
        username = request.POST.get('name')
        pwd = request.POST.get('pwd')
        rem = request.POST.get('remember')
        user = User.objects.filter(username=username, password=pwd)
        if user:
            request.session['flag'] = 1
            res = JsonResponse({"msg": "登录成功", "status": 1})
            if rem:
                res.set_cookie('name', username, max_age=7 * 24 * 3600)
                res.set_cookie('password', pwd, max_age=7 * 24 * 3600)
            return res
        else:
            return JsonResponse({"msg": "用户名或密码错误", "status": 0})
    except:
        return JsonResponse({"msg": "登录失败", "status": 0})


def register(request):
    return render(request, 'regist.html')


def register_logic(request):
    num = request.POST.get('number').lower()
    num2 = request.session.get('code').lower()
    if num == num2:
        username = request.POST.get('username')
        realname = request.POST.get('name')
        pwd = request.POST.get('pwd')
        sex = request.POST.get('sex')
        user = User.objects.filter(username='username')
        if user:
            return HttpResponse('注册失败,用户名重复')
        else:
            User.objects.create(username=username, realname=realname, password=pwd, gender=sex)
            return redirect('user:login')
    else:
        return HttpResponse('验证码错误')


def get_captcha(request):
    img = ImageCaptcha()
    code = random.sample(string.ascii_letters + string.digits, 5)
    code = ''.join(code)
    request.session['code'] = code
    data = img.generate(code)
    return HttpResponse(data, 'image/png')


def log_out(request):
    del request.session['flag']
    res = redirect('user:login')
    res.set_cookie('name', '', max_age=1)
    res.set_cookie('password', '', max_age=1)
    return res


def get_username(request):
    time.sleep(1)
    username = request.GET.get('username')
    if username == '':
        return JsonResponse({"status": 0})
    user = User.objects.filter(username=username)
    if user:
        return JsonResponse({"status": 0})
    else:
        return JsonResponse({"status": 1})


def get_code(request):
    time.sleep(1)
    code = request.GET.get('code')
    code1 = request.session.get('code')
    if code.lower() == code1.lower():
        return JsonResponse({"status": 1})
    else:
        return JsonResponse({"status": 0})

EMS/templates/addEmp.html
{% extends 'base.html' %}
<!DOCTYPE html PUBLIC "-//W3C//DTD HTML 4.01 Transitional//EN" "http://www.w3.org/TR/html4/loose.dtd">
<html>
	<head>
        {% block title %}
		<title>添加员工</title>
        {% endblock %}
	</head>

	<body>
	{% block body %}
				<div id="content">
					<p id="whereami">
					</p>
					<h1>
						添加员工信息:
					</h1>
					<form action="{% url 'manage:confirm_add' %}" method="post" enctype="multipart/form-data">
                        {% csrf_token %}
						<table cellpadding="0" cellspacing="0" border="0"
							class="form_table">
							<tr>
								<td valign="middle" align="right">
									姓名:
								</td>
								<td valign="middle" align="left">
									<input type="text" class="inputgri" name="name" />
								</td>
							</tr>
							<tr>
								<td valign="middle" align="right">
									工资:
								</td>
								<td valign="middle" align="left">
									<input type="text" class="inputgri" name="salary" />
								</td>
							</tr>
							<tr>
								<td valign="middle" align="right">
									年龄:
								</td>
								<td valign="middle" align="left">
									<input type="text" class="inputgri" name="age" />
								</td>
							</tr>
                            <tr>
                                <td  valign="middle" align="left">头像:</td>
                                <td>
                                    <input type="file" name="pic" />
                                </td>
                            </tr>
						</table>
						<p>
							<input type="submit" class="button" value="确认添加" />
						</p>
					</form>
				</div>
{% endblock %}
	</body>
</html>

EMS/templates/base.html
{% block static %}
{% endblock %}
<html lang="en">
<head>
    <meta charset="UTF-8">
    {% block title %}
        <title>Title</title>
    {% endblock %}
<meta http-equiv="Content-Type" content="text/html; charset=UTF-8">
		<link rel="stylesheet" type="text/css"
			href="/static/css/style.css" />
{% block css %}

{% endblock %}
{% block js %}

{% endblock %}
</head>
<body>
		<div id="wrap">
			<div id="top_content">
					<div id="header">
						<div id="rightheader">
							<p id="time">
								<br />
							</p>
						</div>
						<div id="topheader">
							<h1 id="title">
								<a href="#">EMS</a>
							</h1>
                            <span style="float: right" id="time">
                                <script type="text/javascript">
                                    setInterval("document.getElementById('time').innerHTML = new Date().toLocaleString();",1000)
                                </script>
                            </span>
						</div>
						<div id="navigation">
						</div>
					</div>
                {% block body %}

                {% endblock %}
			</div>
			<div id="footer">
				<div id="footer_bg">
					actors1021@qq.com
				</div>
			</div>
		</div>
</body>
</html>

EMS/templates/emplist.html
{% extends 'base.html' %}
{% block static %}
    {% load static %}
{% endblock %}
<!DOCTYPE html PUBLIC "-//W3C//DTD HTML 4.01 Transitional//EN" "http://www.w3.org/TR/html4/loose.dtd">
<html lang="en">
<head>
    {% block title %}
        <title>主页面</title>
    {% endblock %}
    {% block css %}
        <style type="text/css">
            .a {
                width: 20px;
                height: 20px;
                border: 1px solid #e1e2e3;
                cursor: pointer;
                display: inline-block;
                text-align: center;
                line-height: 20px;
            }

            .b {
                border: 0;
                width: 20px;
                height: 20px;
                cursor: pointer;
                display: inline-block;
                text-align: center;
                line-height: 20px;
            }

            a {
                text-decoration: none;
            }
        </style>
    {% endblock %}
    {% block js %}
        <script type="text/javascript" src="/static/jquery/jquery-1.11.1-min.js"></script>
        <script type="text/javascript">
            function f1(id) {
                let b = window.confirm('确认删除?');
                if (b === true){
                    if ("{{ page.object_list.count }}" === "1"){
                        location.href = "{% url 'manage:delete' %}?num="+ "{{ page.number|add:-1 }}"+"&id="+id
                    }else{
                        location.href = "{% url 'manage:delete' %}?num="+"{{ page.number }}"+"&id="+id
                }
            }
            }
            function f2(id) {
                location.href = "{% url 'manage:update' %}?num="+"{{ page.number }}"+"&id="+id
            }
            function f3() {
                location.href = "{% url 'user:log_out' %}";
            }
        </script>
    {% endblock %}
</head>
<body>
{% block body %}
    <div id="content">
        <p id="whereami">
        </p>
        <h1>
            欢迎!
            <span>
        <input type="button" name="log_out" class="button" value="注销 &raquo;" style="float: right" onclick="f3()"/>
    </span>
        </h1>
        <table class="table">
            <tr class="table_header">
                <td>
                    ID
                </td>
                <td>
                    姓名
                </td>
                <td>
                    工资
                </td>
                <td>
                    年龄
                </td>
                <td>
                    头像
                </td>
                <td>
                    操作
                </td>
            </tr>
            {% for i in page.object_list %}
                <tr class="row1">
                    <td id="pk">{{ i.id }}</td>
                    <td>{{ i.name }}</td>
                    <td>{{ i.salary }}</td>
                    <td>{{ i.age }}</td>
                    <td><img src="{% static i.pic.url %}" alt="" style="width: 80px;height: 80px;border-radius: 50%"></td>
                    <td>
                        <a href="javascript:void(0)" class="delete" id="delete" name="delete" onclick="f1({{ i.id }})">删除员工</a>&nbsp;<a
                            href="javascript:void (0)" class="update" onclick="f2({{ i.id }})">更新员工</a>
                    </td>
                </tr>
            {% endfor %}
        </table>
        <div style="text-align: center" id="pagtor">
            {% if page.has_previous %}
                <a href="{% url 'manage:main' %}?num={{ page.previous_page_number }}">上一页</a>
            {% endif %}

            {% for foo in page.paginator.page_range %}
                {% if page.number == foo %}
                    <a class="b" type="page" href="{% url 'manage:main' %}?num={{ foo }}" name="page_now" disabled="">{{ foo }}</a>
                {% else %}
                    <a class="a" type="page" href="{% url 'manage:main' %}?num={{ foo }}">{{ foo }}</a>
                {% endif %}
            {% endfor %}

            {% if page.has_next %}
                <a href="{% url 'manage:main' %}?num={{ page.next_page_number }}">下一页</a>
            {% endif %}
        </div>
        <p style="margin: 15px">
            <input type="button" class="button" value="添加员工 &raquo;" onclick="location.href ='{% url 'manage:add' %}'"/>
        </p>
    </div>
{% endblock %}
</body>
</html>

EMS/templates/login.html
{% extends 'base.html' %}
<html lang="en">
	<head>
        {% block title %}
		<title>登录</title>
        {% endblock %}
    {% block js %}
        <script type="text/javascript" src="/static/jquery/jquery-1.11.1-min.js"></script>
        <script type="text/javascript">
        function register() {
            location.href = "{% url 'user:register' %}"
        }
        function checkUsername() {
            let username = $('[name=name]').val();
            let uPattern = /^[a-zA-Z0-9_]{5,20}$/;
            return uPattern.test(username)
        }
        function checkPassword() {
            let password = $('[name=pwd]').val();
            let pPattern = /^.{6,16}$/;
            return pPattern.test(password)
        }
        function login() {
            let result1 = checkUsername();
            let result2 = checkPassword();
            console.log(result1);
            console.log(result2);
            if (result1 === true && result2 === true){
            $.ajax({
                type:'post',
                url:'{% url 'user:login_logic' %}',
                data:$('form').serialize(),
                success:function (resp) {
                    if (resp.status === 1){
                        location.href = '{% url 'manage:main' %}?num=1'
                    }else if(resp.status === 0){
                        alert(resp.msg)
                    }
                }
            });
            }else{
                alert('用户名或密码不合法')
            }
        }
        </script>
    {% endblock %}
	</head>

	<body>
                {% block body %}
				<div id="content">
					<p id="whereami">
					</p>
					<h1>
						登录
                        <span>
                            <input type="button" name="register" class="button" value="注册 &raquo;" style="float: right" onclick="register()">
                        </span>
					</h1>
					<form action="{% url 'user:login_logic' %}" method="post">
                        {% csrf_token %}
						<table cellpadding="0" cellspacing="0" border="0"
							class="form_table">
							<tr>
								<td valign="middle" align="right">
									用户名:
								</td>
								<td valign="middle" align="left">
									<input type="text" class="inputgri" name="name" placeholder="请输入用户名"/>
								</td>
							</tr>
							<tr>
								<td valign="middle" align="right">
									密码:
								</td>
								<td valign="middle" align="left">
									<input type="password" class="inputgri" name="pwd" placeholder="请输入密码"/>
								</td>
							</tr>
                            <tr>
                                <td><input type="checkbox" name="remember"></td>
                                <td>7天内自动登录</td>
                            </tr>
						</table>
						<p>
							<input type="button" class="button" value="登录 &raquo;" onclick="login()"/>
						</p>
					</form>
				</div>
                {% endblock %}
	</body>
</html>

EMS/templates/regist.html
{% extends 'base.html' %}
<html lang="en">
<head>
    {% block title %}
        <title>注册</title>
    {% endblock %}
    {% block js %}
        <script  type="text/javascript" src="/static/jquery/jquery-1.11.1-min.js"></script>
        <script type="text/javascript">
            let flag1 = false;
            let flag2 = false;
            let flag3 = false;
            let flag4 = false;
            function change() {
                  $('#num').prop('src',"{% url 'user:get_captcha' %}?" + new Date().getTime());
            }

            function f1() {
                $('#td3').html("<img src='/static/images/loading.gif' width='20px'>");

                $.get(
                    '{% url 'user:get_username' %}',
                    'username='+$('input[name="username"]:eq(0)').val(),
                    function (result) {
                        if (result.status === 1) {
                            $('#td3').html("<img src='/static/images/right.jpg' width='20px' id='img1'>");
                            flag1 = true
                        }else if(result.status === 0){
                            $('#td3').html("<img src='/static/images/error_3.jpg' width='20px' id='img1'>");
                            flag1 = false
                        }
                    }
                );
            }
            function f2() {
                let pwd = $("input[name='pwd']:eq(0)").val();
                if(pwd.length<=16 && pwd.length>=6){
                    $('#pwd').html("<img src='/static/images/right.jpg' width='20px' id='img2'>");
                    flag2 = true
                }else{
                    $('#pwd').html("<img src='/static/images/error_3.jpg' width='20px' id='img2'>");
                    flag2 = false
                }
            }
            function f3() {
                let pwd = $("input[name='pwd']:eq(0)").val();
                let pwd1 = $("input[name='pwd1']:eq(0)").val();
                if(pwd1 ===pwd){
                   $('#pwd1').html("<img src='/static/images/right.jpg' width='20px' id='img3'>");
                    flag3 = true
                }else{
                    $('#pwd1').html("<img src='/static/images/error_3.jpg' width='20px' id='img3'>");
                    flag3 = false
                }
            }
            function f4() {
                $('#code').html("<img src='/static/images/loading.gif' width='20px'>");
                let code = $('input[name="number"]:eq(0)').val();
                $.get(
                  '{% url 'user:get_code' %}',
                  'code='+code,
                  function (result) {
                      if(result.status === 1) {
                          $('#code').html("<img src='/static/images/right.jpg' width='20px' id='img4'>");
                          flag4 = true
                      }else if (result.status === 0){
                          $('#code').html("<img src='/static/images/error_3.jpg' width='20px' id='img4'>");
                          flag4 = false
                      }
                  }
                );
            }
            function f5() {
                if (flag1 === true && flag2 === true && flag3 === true && flag4 === true){
                    location.href = "{% url 'user:register_logic' %}"
                }else{
                    alert('数据不合法')
                }
            }
            function login() {
                location.href = "{% url 'user:login' %}"
            }
        </script>
    {% endblock %}
</head>
<body>
{% block body %}
    <div id="content">
        <p id="whereami">
        </p>
        <h1>
            注册
            <span>
                <input type="button" name="login" class="button" value="登录 &raquo;" style="float: right" onclick="login()"/>
            </span>
        </h1>
        <form action="{% url 'user:register_logic' %}" method="post">
            {% csrf_token %}
            <table cellpadding="0" cellspacing="0" border="0"
                   class="form_table">
                <tr>
                    <td valign="middle" align="right" id="td1">
                        用户名:
                    </td>
                    <td valign="middle" align="left">
                        <input type="text" class="inputgri" name="username" onblur="f1()" placeholder="请输入4-16位的用户名"/>
                    </td>
                    <td id="td3"> </td>
                </tr>
                <tr>
                    <td valign="middle" align="right">
                        真实姓名:
                    </td>
                    <td valign="middle" align="left">
                        <input type="text" class="inputgri" name="name" placeholder="请输入你的姓名"/>
                    </td>
                </tr>
                <tr>
                    <td valign="middle" align="right">
                        密码:
                    </td>
                    <td valign="middle" align="left">
                        <input type="password" class="inputgri" name="pwd" onblur="f2()" placeholder="请输入6-16位的密码"/>
                    </td>
                    <td id="pwd"></td>
                </tr>
                <tr>
                    <td valign="middle" align="right">
                        确认密码:
                    </td>
                    <td valign="middle" align="right">
                        <input type="password" class="inputgri" name="pwd1" onblur="f3()" placeholder="请再次确认你的密码"/>
                    </td>
                    <td id="pwd1">请确认你的密码</td>
                </tr>
                <tr>
                    <td valign="middle" align="right">
                        性别:
                    </td>
                    <td valign="middle" align="left">
                        男
                        <input type="radio" class="inputgri" name="sex" value="男" checked="checked"/>
                        女
                        <input type="radio" class="inputgri" name="sex" value="女"/>
                    </td>
                </tr>

                <tr>
                    <td valign="middle" align="right">
                        验证码:
                        <img id="num" src="{% url 'user:get_captcha' %}" width="80" alt="无法加载图片"/>
                        <a href="javascript:void(0);" onclick="change()">换一张</a>
                    </td>
                    <td valign="middle" align="left">
                        <input type="text" class="inputgri" name="number" onblur="f4()" placeholder="请输入你的验证码"/>
                    </td>
                    <td id="code"></td>
                </tr>
            </table>
            <p>
                <input type="button" class="button" value="注册 &raquo;" onclick="f5()"/>
            </p>
        </form>
    </div>
{% endblock %}
</body>
</html>

EMS/templates/updateEmp.html
{% extends 'base.html' %}
{% block static %}
    {% load static %}
{% endblock %}
<!DOCTYPE html PUBLIC "-//W3C//DTD HTML 4.01 Transitional//EN" "http://www.w3.org/TR/html4/loose.dtd">
<html lang="en">
	<head>
        {% block title%}
		<title>更新员工信息</title>
        {% endblock %}
{% block js %}
    <script type="text/javascript">
    function f1() {
        let a = document.getElementsByTagName('form')[0];
        a.action = a.action + document.getElementById('pk').innerText;
        if (confirm('确认更新?') === true){
            document.forms[0].submit()
        }
    }
    </script>
    {% endblock %}
	</head>

	<body>
    {% block body %}
				<div id="content">
					<p id="whereami">
					</p>
					<h1>
						更新员工信息:
					</h1>
					<form action="{% url 'manage:confrim_update' %}?id=" method="post" enctype="multipart/form-data">
                        {% csrf_token %}
						<table cellpadding="0" cellspacing="0" border="0"
							class="form_table">
							<tr>
								<td valign="middle" align="right">
									id:
								</td>
								<td valign="middle" align="left" id="pk">
									{{ employee.0.pk }}
								</td>
							</tr>
							<tr>
								<td valign="middle" align="right">
									姓名:
								</td>
								<td valign="middle" align="left">
									<input type="text" class="inputgri" name="name" value="{{ employee.0.name }}"/>
								</td>
							</tr>
							<tr>
								<td valign="middle" align="right">
									工资:
								</td>
								<td valign="middle" align="left">
									<input type="text" class="inputgri" name="salary" value="{{ employee.0.salary }}"/>
								</td>
							</tr>
							<tr>
								<td valign="middle" align="right">
									年龄:
								</td>
								<td valign="middle" align="left">
									<input type="text" class="inputgri" name="age" value="{{ employee.0.age }}"/>
								</td>
							</tr>
                            <tr>
                               <td valign="middle" align="right">头像:</td>
                                <td><img src="{% static employee.0.pic.url %}" alt="" style="width: 80px;height: 80px;border-radius: 50%">
                                    <input type="file" name="pic" alt="{% static employee.0.pic.url %}"/></td>
                            </tr>
						</table>
						<p>
							<input type="button" class="button" value="确认更新" onclick="f1()"/>
						</p>
					</form>
				</div>
{% endblock %}
	</body>
</html>